spring.kafka.bootstrap-servers=172.31.100.92:9092

aws.s3.bucket-name=ecommerce-bucket-demo251923
aws.s3.base-url=https://ecommerce-bucket-demo251923.s3.eu-north-1.amazonaws.com
aws.region=eu-north-1
